/// Size of a Realtek USB RX descriptor before any PHY status and payload bytes.
pub const RX_DESC_SIZE: usize = 24;
/// Default native USB bulk-IN transfer size used by the receiver.
pub const DEFAULT_RX_TRANSFER_SIZE: usize = 32 * 1024;

/// Realtek USB RX descriptor layout family.
///
/// Jaguar1 is used by RTL8812AU/RTL8821AU and the existing RTL8814AU path in
/// this project. Jaguar2 and Jaguar3 use the common 24-byte HalMAC 88xx
/// descriptor while moving several fields from the Jaguar1 layout.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum RxDescriptorKind {
    /// RTL8812AU/RTL8821AU/RTL8814AU-style descriptor layout.
    #[default]
    Jaguar1,
    /// RTL8812BU/RTL8822BU common HalMAC descriptor layout.
    Jaguar2,
    /// RTL8812CU/EU and RTL8822CU/EU descriptor layout.
    Jaguar3,
}

/// Type of packet carried by a Realtek RX descriptor.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RxPacketType {
    /// Normal received 802.11 frame.
    NormalRx,
    /// Command-to-host report generated by the chip firmware.
    C2hPacket,
}

/// Parsed metadata from a Realtek USB RX descriptor.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RxPacketAttrib {
    /// Number of payload bytes following descriptor, PHY status, and shift bytes.
    pub pkt_len: u16,
    /// Whether PHY status bytes are present after the descriptor.
    pub physt: bool,
    /// Driver-info/PHY-status byte count.
    pub drvinfo_sz: u8,
    /// Extra alignment shift before payload bytes.
    pub shift_sz: u8,
    /// Whether the original 802.11 frame had QoS metadata.
    pub qos: bool,
    /// Realtek priority field.
    pub priority: u8,
    /// More-data bit from the descriptor.
    pub mdata: bool,
    /// 802.11 sequence number reported by the descriptor.
    pub seq_num: u16,
    /// 802.11 fragment number reported by the descriptor.
    pub frag_num: u8,
    /// More-fragments bit from the descriptor.
    pub mfrag: bool,
    /// Whether the chip reports the packet as decrypted.
    pub bdecrypted: bool,
    /// Realtek encryption type field.
    pub encrypt: u8,
    /// Hardware-reported CRC/FCS failure.
    pub crc_err: bool,
    /// Hardware-reported ICV failure.
    pub icv_err: bool,
    /// TSF low timestamp from the descriptor.
    pub tsfl: u32,
    /// Realtek data-rate code.
    pub data_rate: u8,
    /// Realtek bandwidth code.
    pub bw: u8,
    /// STBC flag from PHY status.
    pub stbc: u8,
    /// LDPC flag from PHY status.
    pub ldpc: u8,
    /// Short guard interval flag from PHY status.
    pub sgi: u8,
    /// Scrambler seed from PHY status.
    pub scrambler: u8,
    /// Path-A carrier-frequency-offset tail from OFDM PHY status.
    ///
    /// Realtek reports this as a signed hardware code. The vendor conversion
    /// is approximately `raw * 2.5 kHz` at the ordinary 20 MHz clock rate.
    pub cfo_tail: i8,
    /// Whether this MPDU arrived inside an A-MPDU aggregate.
    pub paggr: bool,
    /// HalMAC two-bit received-PPDU counter.
    ///
    /// Consecutive aggregated MPDUs with the same counter value were received
    /// in one PPDU. Jaguar1 descriptors do not expose this counter.
    pub ppdu_cnt: u8,
    /// Per-path raw RSSI readings when available.
    pub rssi: [u8; 4],
    /// Per-path raw SNR readings when available.
    pub snr: [i8; 4],
    /// Per-path raw EVM readings when available.
    pub evm: [i8; 4],
    /// Whether this descriptor carries a received frame or a C2H report.
    pub pkt_rpt_type: RxPacketType,
}

impl Default for RxPacketAttrib {
    fn default() -> Self {
        Self {
            pkt_len: 0,
            physt: false,
            drvinfo_sz: 0,
            shift_sz: 0,
            qos: false,
            priority: 0,
            mdata: false,
            seq_num: 0,
            frag_num: 0,
            mfrag: false,
            bdecrypted: false,
            encrypt: 0,
            crc_err: false,
            icv_err: false,
            tsfl: 0,
            data_rate: 0,
            bw: 0,
            stbc: 0,
            ldpc: 0,
            sgi: 0,
            scrambler: 0,
            cfo_tail: 0,
            paggr: false,
            ppdu_cnt: 0,
            rssi: [0; 4],
            snr: [0; 4],
            evm: [0; 4],
            pkt_rpt_type: RxPacketType::NormalRx,
        }
    }
}

/// One packet extracted from a Realtek USB RX aggregate.
#[derive(Debug, Clone, Copy)]
pub struct RealtekRxPacket<'a> {
    /// Parsed descriptor metadata.
    pub attrib: RxPacketAttrib,
    /// Borrowed packet bytes after descriptor, PHY status, and alignment shift.
    pub data: &'a [u8],
}

impl RealtekRxPacket<'_> {
    /// Return a beacon/probe-response transmitter TSF stamped by the remote MAC.
    ///
    /// The 64-bit little-endian value at MPDU bytes 24 through 31 is inserted
    /// at TX egress by the remote hardware. Pair it with [`RxPacketAttrib::tsfl`]
    /// for one-way hardware clock synchronization.
    pub fn tx_egress_tsf(&self) -> Option<u64> {
        tx_egress_tsf(self.data)
    }
}

/// Parse the hardware TX-egress TSF from an 802.11 beacon or probe response.
pub fn tx_egress_tsf(frame: &[u8]) -> Option<u64> {
    if frame.len() < 32 || !matches!(frame[0], 0x80 | 0x50) {
        return None;
    }
    Some(u64::from_le_bytes(frame[24..32].try_into().ok()?))
}

/// Parsed command-to-host report carried in an RX aggregate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct C2hPacket<'a> {
    /// Firmware command/report identifier.
    pub cmd_id: u8,
    /// Optional sequence byte when the report includes one.
    pub seq: Option<u8>,
    /// Remaining C2H payload bytes.
    pub payload: &'a [u8],
}

/// RTL8814A transmit status report extracted from a C2H packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TxStatusReport8814 {
    /// Offset at which this report was found in the C2H payload.
    pub header_offset: usize,
    /// Hardware queue selector.
    pub queue_select: u8,
    /// Whether the transmitted packet was broadcast.
    pub packet_broadcast: bool,
    /// Whether the packet exceeded the lifetime limit.
    pub lifetime_over: bool,
    /// Whether the packet exceeded the retry limit.
    pub retry_over: bool,
    /// MAC ID associated with the report.
    pub mac_id: u8,
    /// Number of data retries reported by hardware.
    pub data_retry_count: u8,
    /// Queue residency time in microseconds.
    pub queue_time_us: u32,
    /// Final data-rate code used by hardware.
    pub final_data_rate: u8,
}

/// Firmware format used for a decoded per-frame TX status report.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TxReportFormat {
    /// Six-byte RTL8812/RTL8821 CCX report after the two-byte C2H envelope.
    Jaguar1,
    /// Sixteen-byte HalMAC extended CCX report including its four-byte header.
    Halmac,
}

/// Per-frame firmware TX status returned when `SPE_RPT` is set.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TxReport {
    /// On-wire report layout.
    pub format: TxReportFormat,
    /// Completion state: zero means delivered/completed, one means retry-drop.
    pub state: u8,
    /// Whether the transmitted frame was broadcast or multicast.
    pub bmc: bool,
    /// MAC ID associated with the transmission.
    pub mac_id: u8,
    /// Hardware queue selector.
    pub queue_select: u8,
    /// Number of data retransmissions used.
    pub data_retries: u8,
    /// Number of RTS retries, available on HalMAC reports.
    pub rts_retries: u8,
    /// Raw firmware queue-residency value.
    pub queue_time_raw: u16,
    /// Final descriptor rate used by hardware.
    pub final_rate: u8,
    /// HalMAC echo of the descriptor `SW_DEFINE` low byte.
    pub tag: u8,
    /// Number of reports firmware dropped before this HalMAC report.
    pub missed_reports: u8,
}

impl TxReport {
    /// Whether firmware reports successful completion.
    pub const fn delivered(self) -> bool {
        self.state == 0
    }

    /// Jaguar1 queue time converted from 256-microsecond units.
    pub const fn queue_time_us(self) -> Option<u32> {
        match self.format {
            TxReportFormat::Jaguar1 => Some(self.queue_time_raw as u32 * 256),
            TxReportFormat::Halmac => None,
        }
    }
}

/// Error returned while parsing Realtek RX aggregates.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AggregateError {
    /// Fewer than `RX_DESC_SIZE` bytes were available for a descriptor.
    DescriptorTooShort,
    /// Descriptor payload length points beyond the remaining aggregate bytes.
    InvalidPacketLength {
        /// Packet length read from descriptor.
        pkt_len: u16,
        /// Descriptor + metadata + packet offset implied by the descriptor.
        pkt_offset: usize,
        /// Bytes remaining in the aggregate at the current descriptor.
        remaining: usize,
    },
}

/// Structural evidence collected while splitting one Realtek USB RX aggregate.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct RxAggregateDiagnostics {
    /// Complete descriptors parsed from the transfer.
    pub descriptors: usize,
    /// Bytes left after the final complete descriptor/aligned packet.
    pub trailing_bytes: usize,
    /// Non-zero bytes in the trailing region, which can indicate truncation.
    pub trailing_nonzero_bytes: usize,
    /// Alignment bytes skipped between complete packets.
    pub alignment_padding_bytes: usize,
    /// Expected final alignment bytes absent from the USB completion.
    ///
    /// A non-zero value is valid when hardware omits padding after the final
    /// packet, but retaining it makes native/WebUSB trace comparison explicit.
    pub final_alignment_shortfall_bytes: usize,
}

impl std::fmt::Display for AggregateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::DescriptorTooShort => write!(f, "RX descriptor is shorter than {RX_DESC_SIZE} bytes"),
            Self::InvalidPacketLength {
                pkt_len,
                pkt_offset,
                remaining,
            } => write!(
                f,
                "invalid RX packet length: pkt_len={pkt_len}, pkt_offset={pkt_offset}, remaining={remaining}"
            ),
        }
    }
}

impl std::error::Error for AggregateError {}

/// Parse a single Realtek RX descriptor.
pub fn parse_rx_descriptor(desc: &[u8]) -> Result<RxPacketAttrib, AggregateError> {
    parse_rx_descriptor_with_kind(desc, RxDescriptorKind::Jaguar1)
}

/// Parse a single Realtek RX descriptor using an explicit layout.
pub fn parse_rx_descriptor_with_kind(
    desc: &[u8],
    kind: RxDescriptorKind,
) -> Result<RxPacketAttrib, AggregateError> {
    if desc.len() < RX_DESC_SIZE {
        return Err(AggregateError::DescriptorTooShort);
    }

    let d0 = le32(desc, 0);
    let d1 = le32(desc, 4);
    let d2 = le32(desc, 8);
    let d3 = le32(desc, 12);
    let d4 = le32(desc, 16);
    let d5 = le32(desc, 20);

    let mut attrib = RxPacketAttrib {
        pkt_len: bits(d0, 0, 14) as u16,
        crc_err: bits(d0, 14, 1) != 0,
        icv_err: bits(d0, 15, 1) != 0,
        drvinfo_sz: (bits(d0, 16, 4) * 8) as u8,
        shift_sz: bits(d0, 24, 2) as u8,
        physt: bits(d0, 26, 1) != 0,
        data_rate: bits(d3, 0, 7) as u8,
        paggr: bits(d1, 15, 1) != 0,
        ppdu_cnt: if kind == RxDescriptorKind::Jaguar1 {
            0
        } else {
            bits(d2, 29, 2) as u8
        },
        pkt_rpt_type: if bits(d2, 28, 1) != 0 {
            RxPacketType::C2hPacket
        } else {
            RxPacketType::NormalRx
        },
        ..Default::default()
    };

    // DW5 carries TSF-low on all three USB descriptor generations.
    attrib.tsfl = d5;

    if kind == RxDescriptorKind::Jaguar1 {
        attrib.encrypt = bits(d0, 20, 3) as u8;
        attrib.qos = bits(d0, 23, 1) != 0;
        attrib.bdecrypted = bits(d0, 27, 1) == 0;
        attrib.priority = bits(d1, 8, 4) as u8;
        attrib.mdata = bits(d1, 26, 1) != 0;
        attrib.mfrag = bits(d1, 27, 1) != 0;
        attrib.seq_num = bits(d2, 0, 12) as u16;
        attrib.frag_num = bits(d2, 12, 4) as u8;
        attrib.sgi = bits(d4, 0, 1) as u8;
        attrib.ldpc = bits(d4, 1, 1) as u8;
        attrib.stbc = bits(d4, 2, 1) as u8;
        attrib.bw = bits(d4, 4, 2) as u8;
        attrib.scrambler = bits(d4, 9, 7) as u8;
    }

    Ok(attrib)
}

/// Split a Realtek USB bulk-IN transfer into packet descriptors and payloads.
///
/// Realtek devices aggregate one or more RX descriptors into each USB transfer.
/// Each returned packet borrows from `buf`, so callers can parse metadata without
/// copying frame bytes.
pub fn parse_rx_aggregate(buf: &[u8]) -> Result<Vec<RealtekRxPacket<'_>>, AggregateError> {
    parse_rx_aggregate_with_kind(buf, RxDescriptorKind::Jaguar1)
}

/// Split a Realtek USB bulk-IN transfer using an explicit RX descriptor layout.
pub fn parse_rx_aggregate_with_kind(
    buf: &[u8],
    kind: RxDescriptorKind,
) -> Result<Vec<RealtekRxPacket<'_>>, AggregateError> {
    parse_rx_aggregate_with_kind_diagnostics(buf, kind).map(|(packets, _)| packets)
}

/// Split a Realtek USB bulk-IN transfer and retain aggregate-layout evidence.
pub fn parse_rx_aggregate_with_kind_diagnostics(
    buf: &[u8],
    kind: RxDescriptorKind,
) -> Result<(Vec<RealtekRxPacket<'_>>, RxAggregateDiagnostics), AggregateError> {
    let mut packets = Vec::new();
    let mut diagnostics = RxAggregateDiagnostics::default();
    let mut offset = 0usize;

    while offset < buf.len() {
        let remaining = buf.len() - offset;
        if remaining < RX_DESC_SIZE {
            diagnostics.trailing_bytes = remaining;
            diagnostics.trailing_nonzero_bytes =
                buf[offset..].iter().filter(|byte| **byte != 0).count();
            break;
        }

        let desc = &buf[offset..offset + RX_DESC_SIZE];
        let mut attrib = parse_rx_descriptor_with_kind(desc, kind)?;
        diagnostics.descriptors = diagnostics.descriptors.saturating_add(1);
        let data_start =
            offset + RX_DESC_SIZE + attrib.drvinfo_sz as usize + attrib.shift_sz as usize;
        let pkt_offset = RX_DESC_SIZE
            + attrib.drvinfo_sz as usize
            + attrib.shift_sz as usize
            + attrib.pkt_len as usize;
        if attrib.pkt_len == 0 || pkt_offset > remaining {
            return Err(AggregateError::InvalidPacketLength {
                pkt_len: attrib.pkt_len,
                pkt_offset,
                remaining,
            });
        }

        if attrib.pkt_rpt_type == RxPacketType::NormalRx {
            let phy_start = offset + RX_DESC_SIZE;
            let phy_end = phy_start + attrib.drvinfo_sz as usize;
            parse_phy_status(&mut attrib, &buf[phy_start..phy_end], kind);
        }

        let data_end = data_start + attrib.pkt_len as usize;
        packets.push(RealtekRxPacket {
            attrib,
            data: &buf[data_start..data_end],
        });

        let aligned = round_up_8(pkt_offset);
        if aligned >= remaining {
            diagnostics.final_alignment_shortfall_bytes = aligned.saturating_sub(remaining);
            break;
        }
        diagnostics.alignment_padding_bytes = diagnostics
            .alignment_padding_bytes
            .saturating_add(aligned.saturating_sub(pkt_offset));
        offset += aligned;
    }

    Ok((packets, diagnostics))
}

/// Parse a C2H report header from a Realtek RX packet payload.
pub fn parse_c2h_packet(data: &[u8]) -> Option<C2hPacket<'_>> {
    let (&cmd_id, rest) = data.split_first()?;
    let seq = rest.first().copied();
    let payload = if rest.len() > 1 { &rest[1..] } else { rest };
    Some(C2hPacket {
        cmd_id,
        seq,
        payload,
    })
}

/// Parse an RTL8812/RTL8821 six-byte CCX report payload.
///
/// `payload` starts after the ordinary two-byte C2H command/sequence envelope.
pub fn parse_tx_report_jaguar1(payload: &[u8]) -> Option<TxReport> {
    let p = payload.get(..6)?;
    let lifetime_over = p[0] & (1 << 6) != 0;
    let retry_over = p[0] & (1 << 7) != 0;
    Some(TxReport {
        format: TxReportFormat::Jaguar1,
        state: if retry_over {
            1
        } else if lifetime_over {
            2
        } else {
            0
        },
        bmc: p[0] & (1 << 5) != 0,
        mac_id: p[1],
        queue_select: p[0] & 0x1f,
        data_retries: p[2] & 0x3f,
        rts_retries: 0,
        queue_time_raw: u16::from_le_bytes([p[3], p[4]]),
        final_rate: p[5],
        tag: 0,
        missed_reports: 0,
    })
}

/// Return whether bytes contain a HalMAC extended CCX report.
pub fn is_tx_report_halmac(data: &[u8]) -> bool {
    data.len() >= 16 && data[0] == 0xff && data[2] == 0x0f
}

/// Parse a HalMAC extended CCX report including its four-byte C2H header.
pub fn parse_tx_report_halmac(data: &[u8]) -> Option<TxReport> {
    if !is_tx_report_halmac(data) {
        return None;
    }
    let d1 = u32::from_le_bytes(data[4..8].try_into().ok()?);
    let d2 = u32::from_le_bytes(data[8..12].try_into().ok()?);
    let d3 = u32::from_le_bytes(data[12..16].try_into().ok()?);
    Some(TxReport {
        format: TxReportFormat::Halmac,
        state: bits(d2, 30, 2) as u8,
        bmc: bits(d2, 29, 1) != 0,
        mac_id: bits(d1, 16, 7) as u8,
        queue_select: bits(d1, 8, 5) as u8,
        data_retries: bits(d3, 0, 6) as u8,
        rts_retries: bits(d2, 24, 4) as u8,
        queue_time_raw: bits(d2, 0, 16) as u16,
        final_rate: bits(d3, 8, 7) as u8,
        tag: bits(d2, 16, 8) as u8,
        missed_reports: bits(d1, 13, 3) as u8,
    })
}

/// Parse a CCX TX report from one Realtek RX packet and descriptor generation.
///
/// Jaguar1 reports use an ordinary `0x03` C2H envelope. Jaguar2/3 reports use
/// the extended HalMAC packet beginning with `0xff, seq, 0x0f`.
pub fn parse_tx_report_packet(
    packet: &RealtekRxPacket<'_>,
    descriptor_kind: RxDescriptorKind,
) -> Option<TxReport> {
    match descriptor_kind {
        RxDescriptorKind::Jaguar1 => {
            let c2h = parse_c2h_packet(packet.data)?;
            (c2h.cmd_id == 0x03)
                .then(|| parse_tx_report_jaguar1(c2h.payload))
                .flatten()
        }
        RxDescriptorKind::Jaguar2 | RxDescriptorKind::Jaguar3 => {
            parse_tx_report_halmac(packet.data)
        }
    }
}

/// Parse RTL8814A TX status reports from a C2H payload.
pub fn parse_8814_tx_status_reports(data: &[u8]) -> Vec<TxStatusReport8814> {
    [1usize, 2usize]
        .into_iter()
        .filter_map(|offset| parse_8814_tx_status_report_at(data, offset))
        .collect()
}

/// Parse one RTL8814A TX status report at a known payload offset.
pub fn parse_8814_tx_status_report_at(
    data: &[u8],
    header_offset: usize,
) -> Option<TxStatusReport8814> {
    let h = data.get(header_offset..header_offset + 6)?;
    let queue_time_raw = u16::from_le_bytes([h[3], h[4]]);
    Some(TxStatusReport8814 {
        header_offset,
        queue_select: h[0] & 0x1f,
        packet_broadcast: h[0] & (1 << 5) != 0,
        lifetime_over: h[0] & (1 << 6) != 0,
        retry_over: h[0] & (1 << 7) != 0,
        mac_id: h[1],
        data_retry_count: h[2] & 0x3f,
        queue_time_us: u32::from(queue_time_raw) * 256,
        final_data_rate: h[5],
    })
}

const fn round_up_8(value: usize) -> usize {
    (value + 7) & !7
}

fn le32(bytes: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes(
        bytes[offset..offset + 4]
            .try_into()
            .expect("descriptor length checked"),
    )
}

const fn bits(word: u32, offset: u8, len: u8) -> u32 {
    if len == 32 {
        word
    } else {
        (word >> offset) & ((1u32 << len) - 1)
    }
}

fn parse_phy_status(attrib: &mut RxPacketAttrib, phy: &[u8], kind: RxDescriptorKind) {
    if kind != RxDescriptorKind::Jaguar1 {
        parse_phy_status_jaguar23(attrib, phy, kind);
        return;
    }
    if phy.len() < 2 {
        return;
    }

    attrib.rssi[0] = phy[0];
    attrib.rssi[1] = phy[1];

    if phy.len() > 9 {
        attrib.cfo_tail = phy[9] as i8;
    }

    if phy.len() < 28 {
        return;
    }

    attrib.rssi[2] = phy[23];
    attrib.rssi[3] = phy[24];
    attrib.snr[0] = phy[15] as i8;
    attrib.snr[1] = phy[16] as i8;
    attrib.snr[2] = phy[21] as i8;
    attrib.snr[3] = phy[22] as i8;
    attrib.evm[0] = phy[13] as i8;
    attrib.evm[1] = phy[14] as i8;
    attrib.evm[2] = phy[19] as i8;
    attrib.evm[3] = phy[20] as i8;
}

fn parse_phy_status_jaguar23(attrib: &mut RxPacketAttrib, phy: &[u8], kind: RxDescriptorKind) {
    if phy.len() < 28 {
        return;
    }
    let is_cck = if kind == RxDescriptorKind::Jaguar3 {
        phy[0] & 0x0f == 0
    } else {
        attrib.data_rate <= 3
    };
    if is_cck {
        attrib.rssi[0] = phy[1];
        return;
    }
    attrib.rssi.copy_from_slice(&phy[1..5]);
    attrib.ldpc = (phy[7] >> 5) & 1;
    attrib.stbc = (phy[7] >> 6) & 1;
    let l_rxsc = phy[5] & 0x0f;
    let ht_rxsc = (phy[5] >> 4) & 0x0f;
    let rxsc = if (4..=11).contains(&attrib.data_rate) {
        l_rxsc
    } else {
        ht_rxsc
    };
    attrib.bw = if rxsc >= 13 {
        2
    } else if rxsc >= 9 {
        1
    } else {
        0
    };

    // Jaguar3 pages other than type 1 reuse these bytes for unrelated data.
    if kind == RxDescriptorKind::Jaguar2 || phy[0] & 0x0f == 1 {
        attrib.cfo_tail = phy[20] as i8;
        for path in 0..4 {
            attrib.evm[path] = phy[16 + path] as i8;
            attrib.snr[path] = phy[24 + path] as i8;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn put_bits(word: &mut u32, offset: u8, len: u8, value: u32) {
        let mask = ((1u32 << len) - 1) << offset;
        *word = (*word & !mask) | ((value << offset) & mask);
    }

    fn descriptor(pkt_len: u16, drvinfo_units: u8, shift: u8, seq: u16) -> [u8; RX_DESC_SIZE] {
        let mut desc = [0; RX_DESC_SIZE];
        let mut d0 = 0u32;
        put_bits(&mut d0, 0, 14, pkt_len as u32);
        put_bits(&mut d0, 16, 4, drvinfo_units as u32);
        put_bits(&mut d0, 24, 2, shift as u32);
        let mut d2 = 0u32;
        put_bits(&mut d2, 0, 12, seq as u32);
        desc[0..4].copy_from_slice(&d0.to_le_bytes());
        desc[8..12].copy_from_slice(&d2.to_le_bytes());
        desc
    }

    fn jaguar3_descriptor(
        pkt_len: u16,
        drvinfo_units: u8,
        shift: u8,
        rx_rate: u8,
        c2h: bool,
    ) -> [u8; RX_DESC_SIZE] {
        let mut desc = [0; RX_DESC_SIZE];
        let mut d0 = 0u32;
        put_bits(&mut d0, 0, 14, pkt_len as u32);
        put_bits(&mut d0, 14, 1, 1);
        put_bits(&mut d0, 15, 1, 1);
        put_bits(&mut d0, 16, 4, drvinfo_units as u32);
        put_bits(&mut d0, 24, 2, shift as u32);
        let mut d2 = 0u32;
        put_bits(&mut d2, 28, 1, u32::from(c2h));
        let mut d3 = 0u32;
        put_bits(&mut d3, 0, 7, rx_rate as u32);
        desc[0..4].copy_from_slice(&d0.to_le_bytes());
        desc[8..12].copy_from_slice(&d2.to_le_bytes());
        desc[12..16].copy_from_slice(&d3.to_le_bytes());
        desc
    }

    #[test]
    fn surfaces_aggregation_markers_from_rx_descriptors() {
        for kind in [RxDescriptorKind::Jaguar1, RxDescriptorKind::Jaguar2] {
            let mut desc = descriptor(4, 0, 0, 9);
            let mut d1 = u32::from_le_bytes(desc[4..8].try_into().unwrap());
            put_bits(&mut d1, 15, 1, 1);
            desc[4..8].copy_from_slice(&d1.to_le_bytes());
            let mut d2 = u32::from_le_bytes(desc[8..12].try_into().unwrap());
            put_bits(&mut d2, 29, 2, 3);
            desc[8..12].copy_from_slice(&d2.to_le_bytes());

            let attrib = parse_rx_descriptor_with_kind(&desc, kind).unwrap();
            assert!(attrib.paggr);
            assert_eq!(
                attrib.ppdu_cnt,
                if kind == RxDescriptorKind::Jaguar1 {
                    0
                } else {
                    3
                }
            );
        }
    }

    #[test]
    fn parses_jaguar1_ccx_tx_report() {
        let report = parse_tx_report_jaguar1(&[0x40 | 0x05, 0x2a, 0x3f, 0x34, 0x12, 0x55]).unwrap();

        assert_eq!(report.format, TxReportFormat::Jaguar1);
        assert_eq!(report.state, 2);
        assert!(!report.delivered());
        assert_eq!(report.queue_select, 5);
        assert_eq!(report.mac_id, 0x2a);
        assert_eq!(report.data_retries, 0x3f);
        assert_eq!(report.queue_time_raw, 0x1234);
        assert_eq!(report.queue_time_us(), Some(0x1234 * 256));
        assert_eq!(report.final_rate, 0x55);
    }

    #[test]
    fn parses_halmac_ccx_tx_report() {
        let mut report = [0u8; 16];
        report[0] = 0xff;
        report[2] = 0x0f;
        let d1 = (7u32 << 8) | (3u32 << 13) | (0x45u32 << 16);
        let d2 = 0x1234u32 | (0xabu32 << 16) | (9u32 << 24) | (1u32 << 29);
        let d3 = 0x2au32 | (0x51u32 << 8);
        report[4..8].copy_from_slice(&d1.to_le_bytes());
        report[8..12].copy_from_slice(&d2.to_le_bytes());
        report[12..16].copy_from_slice(&d3.to_le_bytes());

        let parsed = parse_tx_report_halmac(&report).unwrap();
        assert_eq!(parsed.format, TxReportFormat::Halmac);
        assert_eq!(parsed.queue_select, 7);
        assert_eq!(parsed.missed_reports, 3);
        assert_eq!(parsed.mac_id, 0x45);
        assert_eq!(parsed.queue_time_raw, 0x1234);
        assert_eq!(parsed.tag, 0xab);
        assert_eq!(parsed.rts_retries, 9);
        assert!(parsed.bmc);
        assert_eq!(parsed.data_retries, 0x2a);
        assert_eq!(parsed.final_rate, 0x51);
    }

    #[test]
    fn parses_report_from_generation_tagged_rx_packet() {
        let packet = RealtekRxPacket {
            attrib: RxPacketAttrib::default(),
            data: &[0x03, 0x11, 0x05, 0x2a, 0x03, 0x34, 0x12, 0x55],
        };
        let report = parse_tx_report_packet(&packet, RxDescriptorKind::Jaguar1).unwrap();
        assert_eq!(report.mac_id, 0x2a);
        assert_eq!(report.queue_time_raw, 0x1234);
    }

    #[test]
    fn parses_single_rx_packet() {
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&descriptor(4, 0, 0, 77));
        aggregate.extend_from_slice(&[1, 2, 3, 4]);

        let packets = parse_rx_aggregate(&aggregate).unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0].attrib.pkt_len, 4);
        assert_eq!(packets[0].attrib.seq_num, 77);
        assert_eq!(packets[0].data, &[1, 2, 3, 4]);
    }

    #[test]
    fn ignores_short_tail_after_aligned_packet() {
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&descriptor(4, 0, 0, 77));
        aggregate.extend_from_slice(&[1, 2, 3, 4]);
        aggregate.extend_from_slice(&[0, 0, 0, 0]);
        aggregate.extend_from_slice(&[0xde, 0xad, 0xbe, 0xef]);

        let packets = parse_rx_aggregate(&aggregate).unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0].data, &[1, 2, 3, 4]);
    }

    #[test]
    fn rejects_zero_length_descriptor() {
        let aggregate = descriptor(0, 0, 0, 1);

        let err = parse_rx_aggregate(&aggregate).unwrap_err();
        assert_eq!(
            err,
            AggregateError::InvalidPacketLength {
                pkt_len: 0,
                pkt_offset: RX_DESC_SIZE,
                remaining: RX_DESC_SIZE,
            }
        );
    }

    #[test]
    fn rejects_descriptor_payload_past_transfer() {
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&descriptor(8, 0, 0, 1));
        aggregate.extend_from_slice(&[1, 2, 3, 4]);

        let err = parse_rx_aggregate(&aggregate).unwrap_err();
        assert_eq!(
            err,
            AggregateError::InvalidPacketLength {
                pkt_len: 8,
                pkt_offset: RX_DESC_SIZE + 8,
                remaining: RX_DESC_SIZE + 4,
            }
        );
    }

    #[test]
    fn surfaces_crc_and_icv_flags_from_jaguar1_descriptor() {
        let mut desc = descriptor(4, 0, 0, 9);
        let mut d0 = u32::from_le_bytes(desc[0..4].try_into().unwrap());
        put_bits(&mut d0, 14, 1, 1);
        put_bits(&mut d0, 15, 1, 1);
        desc[0..4].copy_from_slice(&d0.to_le_bytes());

        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&desc);
        aggregate.extend_from_slice(&[1, 2, 3, 4]);

        let packets = parse_rx_aggregate(&aggregate).unwrap();
        assert!(packets[0].attrib.crc_err);
        assert!(packets[0].attrib.icv_err);
        assert_eq!(packets[0].data, &[1, 2, 3, 4]);
    }

    #[test]
    fn does_not_decode_payload_as_phy_status_when_drvinfo_absent() {
        let mut payload = vec![0u8; 32];
        payload[0] = 55;
        payload[1] = 66;
        payload[13] = 0x80;
        payload[15] = 0x7f;
        payload[23] = 77;

        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&descriptor(payload.len() as u16, 0, 0, 1));
        aggregate.extend_from_slice(&payload);

        let packets = parse_rx_aggregate(&aggregate).unwrap();
        assert_eq!(packets[0].attrib.rssi, [0; 4]);
        assert_eq!(packets[0].attrib.snr, [0; 4]);
        assert_eq!(packets[0].attrib.evm, [0; 4]);
        assert_eq!(packets[0].data, payload);
    }

    #[test]
    fn parses_phy_status_only_from_driver_info_bytes() {
        let mut phy = vec![0u8; 32];
        phy[0] = 42;
        phy[1] = 43;
        phy[13] = 0xf0;
        phy[14] = 0x0f;
        phy[15] = 0x80;
        phy[16] = 0x7f;
        phy[19] = 0xee;
        phy[20] = 0xdd;
        phy[21] = 0xcc;
        phy[22] = 0xbb;
        phy[23] = 44;
        phy[24] = 45;

        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&descriptor(3, 4, 1, 1));
        aggregate.extend_from_slice(&phy);
        aggregate.push(0xaa);
        aggregate.extend_from_slice(&[1, 2, 3]);

        let packets = parse_rx_aggregate(&aggregate).unwrap();
        assert_eq!(packets[0].attrib.drvinfo_sz, 32);
        assert_eq!(packets[0].attrib.shift_sz, 1);
        assert_eq!(packets[0].attrib.rssi, [42, 43, 44, 45]);
        assert_eq!(packets[0].attrib.snr, [-128, 127, -52, -69]);
        assert_eq!(packets[0].attrib.evm, [-16, 15, -18, -35]);
        assert_eq!(packets[0].data, &[1, 2, 3]);
    }

    #[test]
    fn parses_c2h_packet_header() {
        let packet = parse_c2h_packet(&[0x42, 0x7f, 1, 2]).unwrap();
        assert_eq!(packet.cmd_id, 0x42);
        assert_eq!(packet.seq, Some(0x7f));
        assert_eq!(packet.payload, &[1, 2]);
    }

    #[test]
    fn parses_8814_tx_status_at_devourer_offsets() {
        let bytes = [0xaa, 0x83, 0x09, 0x25, 0x34, 0x12, 0x6c, 0xbb];
        let reports = parse_8814_tx_status_reports(&bytes);
        assert_eq!(reports.len(), 2);
        assert_eq!(reports[0].header_offset, 1);
        assert_eq!(reports[0].queue_select, 3);
        assert!(reports[0].retry_over);
        assert_eq!(reports[0].mac_id, 9);
        assert_eq!(reports[0].data_retry_count, 0x25);
        assert_eq!(reports[0].queue_time_us, 0x1234 * 256);
        assert_eq!(reports[0].final_data_rate, 0x6c);
    }

    #[test]
    fn advances_by_jaguar_eight_byte_alignment() {
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&descriptor(5, 0, 0, 1));
        aggregate.extend_from_slice(&[1, 2, 3, 4, 5]);
        aggregate.extend_from_slice(&[0, 0, 0]);
        aggregate.extend_from_slice(&descriptor(3, 0, 0, 2));
        aggregate.extend_from_slice(&[6, 7, 8]);

        let packets = parse_rx_aggregate(&aggregate).unwrap();
        assert_eq!(packets.len(), 2);
        assert_eq!(packets[0].data, &[1, 2, 3, 4, 5]);
        assert_eq!(packets[1].data, &[6, 7, 8]);
    }

    #[test]
    fn reports_alignment_and_trailing_descriptor_evidence() {
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&descriptor(5, 0, 0, 1));
        aggregate.extend_from_slice(&[1, 2, 3, 4, 5]);
        aggregate.extend_from_slice(&[0, 0, 0]);
        aggregate.extend_from_slice(&[0xaa, 0, 0xbb, 0]);

        let (packets, diagnostics) =
            parse_rx_aggregate_with_kind_diagnostics(&aggregate, RxDescriptorKind::Jaguar1)
                .unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(diagnostics.descriptors, 1);
        assert_eq!(diagnostics.alignment_padding_bytes, 3);
        assert_eq!(diagnostics.trailing_bytes, 4);
        assert_eq!(diagnostics.trailing_nonzero_bytes, 2);
    }

    #[test]
    fn jaguar3_descriptor_matches_devourer_field_positions() {
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&jaguar3_descriptor(4, 1, 2, 0x2c, false));
        aggregate.extend_from_slice(&[41, 42, 0, 0, 0, 0, 0, 0]);
        aggregate.extend_from_slice(&[0xaa, 0xbb]);
        aggregate.extend_from_slice(&[1, 2, 3, 4]);

        let packets = parse_rx_aggregate_with_kind(&aggregate, RxDescriptorKind::Jaguar3).unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0].attrib.pkt_len, 4);
        assert_eq!(packets[0].attrib.drvinfo_sz, 8);
        assert_eq!(packets[0].attrib.shift_sz, 2);
        assert_eq!(packets[0].attrib.data_rate, 0x2c);
        assert!(packets[0].attrib.crc_err);
        assert!(packets[0].attrib.icv_err);
        assert_eq!(packets[0].attrib.pkt_rpt_type, RxPacketType::NormalRx);
        assert_eq!(packets[0].data, &[1, 2, 3, 4]);
    }

    #[test]
    fn jaguar3_c2h_bit_is_report_type() {
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&jaguar3_descriptor(3, 0, 0, 0, true));
        aggregate.extend_from_slice(&[0x61, 0x01, 0x02]);

        let packets = parse_rx_aggregate_with_kind(&aggregate, RxDescriptorKind::Jaguar3).unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0].attrib.pkt_rpt_type, RxPacketType::C2hPacket);
        assert_eq!(packets[0].data, &[0x61, 0x01, 0x02]);
    }

    #[test]
    fn jaguar3_type1_phy_status_uses_jgr3_offsets() {
        let mut phy = [0u8; 32];
        phy[0] = 1;
        phy[1..5].copy_from_slice(&[71, 57, 0, 0]);
        phy[5] = 13 << 4;
        phy[7] = (1 << 5) | (1 << 6);
        phy[16..20].copy_from_slice(&[0xd5, 0x80, 0, 0]);
        phy[20] = 0xf4;
        phy[24..28].copy_from_slice(&[43, 25, 0, 0]);
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&jaguar3_descriptor(3, 4, 0, 13, false));
        aggregate.extend_from_slice(&phy);
        aggregate.extend_from_slice(&[1, 2, 3]);

        let packet = parse_rx_aggregate_with_kind(&aggregate, RxDescriptorKind::Jaguar3)
            .unwrap()
            .remove(0);
        assert_eq!(packet.attrib.rssi, [71, 57, 0, 0]);
        assert_eq!(packet.attrib.evm[0], -43);
        assert_eq!(packet.attrib.cfo_tail, -12);
        assert_eq!(packet.attrib.snr[..2], [43, 25]);
        assert_eq!(packet.attrib.bw, 2);
        assert_eq!((packet.attrib.ldpc, packet.attrib.stbc), (1, 1));
    }

    #[test]
    fn all_generations_surface_descriptor_tsf_low() {
        let mut desc = jaguar3_descriptor(4, 0, 0, 0x2c, false);
        desc[20..24].copy_from_slice(&0x89ab_cdefu32.to_le_bytes());
        for kind in [RxDescriptorKind::Jaguar2, RxDescriptorKind::Jaguar3] {
            let parsed = parse_rx_descriptor_with_kind(&desc, kind).unwrap();
            assert_eq!(parsed.tsfl, 0x89ab_cdef);
        }
    }

    #[test]
    fn parses_beacon_and_probe_response_egress_tsf() {
        let tsf = 0x1122_3344_5566_7788u64;
        for fc0 in [0x80, 0x50] {
            let mut frame = [0u8; 32];
            frame[0] = fc0;
            frame[24..32].copy_from_slice(&tsf.to_le_bytes());
            assert_eq!(tx_egress_tsf(&frame), Some(tsf));
        }
        assert_eq!(tx_egress_tsf(&[0x08; 32]), None);
        assert_eq!(tx_egress_tsf(&[0x80; 31]), None);
    }

    #[test]
    fn jaguar3_non_type1_page_does_not_decode_evm_or_snr() {
        let mut phy = [0u8; 32];
        phy[0] = 2;
        phy[1] = 64;
        phy[16] = 0x80;
        phy[24] = 0x7f;
        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&jaguar3_descriptor(1, 4, 0, 13, false));
        aggregate.extend_from_slice(&phy);
        aggregate.push(0xaa);
        let packet = parse_rx_aggregate_with_kind(&aggregate, RxDescriptorKind::Jaguar3)
            .unwrap()
            .remove(0);
        assert_eq!(packet.attrib.rssi[0], 64);
        assert_eq!(packet.attrib.evm, [0; 4]);
        assert_eq!(packet.attrib.snr, [0; 4]);
    }

    #[test]
    fn c2h_payload_respects_drvinfo_and_shift_offsets() {
        let mut desc = descriptor(3, 1, 2, 0);
        let mut d2 = u32::from_le_bytes(desc[8..12].try_into().unwrap());
        put_bits(&mut d2, 28, 1, 1);
        desc[8..12].copy_from_slice(&d2.to_le_bytes());

        let mut aggregate = Vec::new();
        aggregate.extend_from_slice(&desc);
        aggregate.extend_from_slice(&[0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48]);
        aggregate.extend_from_slice(&[0xaa, 0xbb]);
        aggregate.extend_from_slice(&[0x61, 0x07, 0xcc]);

        let packets = parse_rx_aggregate(&aggregate).unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0].attrib.pkt_rpt_type, RxPacketType::C2hPacket);
        assert_eq!(packets[0].attrib.drvinfo_sz, 8);
        assert_eq!(packets[0].attrib.shift_sz, 2);
        assert_eq!(packets[0].data, &[0x61, 0x07, 0xcc]);
        assert_eq!(
            parse_c2h_packet(packets[0].data),
            Some(C2hPacket {
                cmd_id: 0x61,
                seq: Some(0x07),
                payload: &[0xcc],
            })
        );
    }
}
