const COMMANDS: &[&str] = &["list_devices", "open_device", "close_device"];

fn main() {
    generate_android_supported_devices()
        .expect("failed to generate Android supported Realtek USB device files");

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("android") {
        tauri_plugin::mobile::update_android_manifest(
            "openipc-usb-device-attached",
            "activity",
            r#"<intent-filter>
    <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
</intent-filter>
<meta-data
    android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"
    android:resource="@xml/openipc_usb_device_filter" />"#
                .to_owned(),
        )
        .expect("failed to update generated Android manifest for OpenIPC USB attach handling");
    }

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../../crates/openipc-rtl88xx/src/types.rs");

    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}

fn generate_android_supported_devices() -> std::io::Result<()> {
    use openipc_rtl88xx::SUPPORTED_DEVICES;
    use std::fmt::Write as _;
    use std::path::Path;

    let xml_path = Path::new("android/src/main/res/xml/openipc_usb_device_filter.xml");
    if let Some(parent) = xml_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut xml = String::from(
        r#"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/tauri-plugin-openipc-usb/build.rs from openipc-rtl88xx::SUPPORTED_DEVICES. -->
<resources>
"#,
    );
    for device in SUPPORTED_DEVICES {
        writeln!(
            xml,
            r#"    <usb-device vendor-id="{:04X}" product-id="{:04X}" />"#,
            device.vendor_id, device.product_id
        )
        .expect("write to String cannot fail");
    }
    xml.push_str("</resources>\n");
    std::fs::write(xml_path, xml)?;

    let kotlin_path =
        Path::new("android/src/main/java/dev/openipc/usb/GeneratedSupportedRealtekDevices.kt");
    if let Some(parent) = kotlin_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut kotlin = String::from(
        r#"package dev.openipc.usb

// Generated by plugins/tauri-plugin-openipc-usb/build.rs from openipc-rtl88xx::SUPPORTED_DEVICES.
internal data class SupportedRealtekDevice(
  val vendorId: Int,
  val productId: Int,
  val label: String,
) {
  fun matches(device: android.hardware.usb.UsbDevice): Boolean =
    device.vendorId == vendorId && device.productId == productId
}

internal val supportedRealtekDevices =
  listOf(
"#,
    );
    for device in SUPPORTED_DEVICES {
        writeln!(
            kotlin,
            r#"    SupportedRealtekDevice(0x{:04x}, 0x{:04x}, "{}"),"#,
            device.vendor_id,
            device.product_id,
            escape_kotlin_string(device.label)
        )
        .expect("write to String cannot fail");
    }
    kotlin.push_str("  )\n");
    std::fs::write(kotlin_path, kotlin)?;

    Ok(())
}

fn escape_kotlin_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            _ => escaped.push(ch),
        }
    }
    escaped
}
